spring:
  application:
    name: popspace
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: scott
#    password: tiger
    data:
      redis:
        host: localhost
        port: 6379


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: org.example.shoppingmall_be.util
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

org:
  zerock:
    jwt:
      secret: ${JWT_SECRET}
    hmac:
      secret: ${HMAC_SECRET:default-secret-key}


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${BUCKET_NAME}