spring:
  application:
    name: popspace
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    data:
      redis:
        host: localhost
        port: 6379


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: org.example.shoppingmall_be.util
  configuration:
    map-underscore-to-camel-case: true

org:
  zerock:
    jwt:
      secret: ${JWT_SECRET}
    hmac:
      secret: ${HMAC_SECRET:default-secret-key}


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: us-east-2
    s3:
      bucket: ${BUCKET_NAME}