spring:
  application:
    name: popspace
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    data:
      redis:
        host: ${RESERVATION_REDIS_HOST}
        port: ${RESERVATION_REDIS_PORT}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
        transport:
          protocol: smtp
        debug: false
custom-redis:
    host: ${AUTH_REDIS_HOST}
    port: ${AUTH_REDIS_PORT}




mybatis:
#  mapper-locations: classpath:mapper/**/*.xml
#  type-handlers-package: org.example.shoppingmall_be.util
  configuration:
    map-underscore-to-camel-case: true

org:
  zerock:
    jwt:
      secret: ${JWT_SECRET}
    hmac:
      secret: ${HMAC_SECRET:default-secret-key}


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${BUCKET_NAME}